

spring:
    application:
        name: notification-service
    config:
        import: "optional:configserver:https://config-service-50018270010.development.catalystappsail.in"

    datasource:
        url:
        username:
        password:
        driver-class-name:

    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://accounts.google.com
                    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs


services:
    api-gateway:
        base: http://api-gateway:7000

logging:
    level:
        org:
            springframework:
                security: trace
