
spring:
    application:
        name: application-service
    main:
        allow-circular-references: true
    
logging:
    level:
        org:
            springframework:
                security: trace
            web:
                servlet:
                    i18n: DEBUG
