
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://authorization-server-50019167766.catalystappsail.in

services:
  api-gateway:
    base: https://api-gateway-50018270010.catalystappsail.in

app:
  redis:
    host: renewed-crappie-44493.upstash.io
    port: 44493
    password: ${REDIS_PASSWORD}
  scheduler:
    baseUrl: ${SERVICE_BASE_URL}

logging:
    level:
        org:
            springframework:
                security: trace
            web:
                servlet:
                    i18n: DEBUG
