spring:
  config:
    import: "optional:configserver:http://config-service:8099"

  datasource:
    url:
    username:
    password:
    driver-class-name:

  autoconfigure:
    exclude:
        - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
