
spring:
    application:
        name: application-service
    config:
        import: "configserver:http://localhost:8099"

    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/blog_application
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver

    profiles:
        active: production
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://accounts.google.com
                    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

logging:
    level:
        org:
            springframework:
                security: trace
            web:
                servlet:
                    i18n: DEBUG
