server:
  port: 8082

spring:
  cache:
    type: redis
    redis:
      time-to-live: 300000
  application:
    name: application-service
  main:
    allow-circular-references: true

  data:
    mongodb:
      host: application-mondodb
      port: 27017
      database: application

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://authorization-server-50019167766.catalystappsail.in

services:
  api-gateway:
    base: http://api-gateway:7000

app:
  redis:
    host: redis-service
    port: 6379
    password: ""

logging:
  level:
    org:
      springframework:
        security: trace
      web:
        servlet:
          i18n: DEBUG
