
server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://vigneshwaran4817:hLKybDS12uC4F6Bj@applicationdb.j4suvxj.mongodb.net/ApplicationDB?retryWrites=true&w=majority&appName=ApplicationDB

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
