
spring:
    application:
        name: application-service
    config:
        import: "configserver:http://localhost:8099"
    main:
        allow-circular-references: true

    datasource:
        url:
        username:
        password:
        driver-class-name:

    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://accounts.google.com
                    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

logging:
    level:
        org:
            springframework:
                security: trace
            web:
                servlet:
                    i18n: DEBUG
