server:
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-50018270010.development.catalystappsail.in/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
