
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:9000/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

oauth2:
  server:
    url: http://localhost:9090