
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-50018270010.development.catalystappsail.in/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

oauth2:
  server:
    url: http://localhost:9090