
server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-50018270010.development.catalystappsail.in/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

services:
  api-gateway:
    base: http://api-gateway:7000