
server:
    port: 9000

spring:
    application:
        name: service-registry
eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: false
        fetch_registry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/