version: '3.8'

services:

  application-mondodb:
    container_name: application-mondodb
    image: mongo
    ports: 
      - "27018:27017"
    volumes: 
      - application-mongo:/data/db
    networks:
      - blog-network

  notification-mondodb:
    container_name: notification-mondodb
    image: mongo
    ports: 
      - "27019:27017"
    volumes: 
      - notification-mongo:/data/db
    networks:
      - blog-network
    
  static-service-mondodb:
    container_name: static-service-mondodb
    image: mongo
    ports: 
      - "27020:27017"
    volumes: 
      - static-service-mongo:/data/db
    networks:
      - blog-network

  application-service:
    container_name: application-service
    build:
      context: application-service
      dockerfile: Dockerfile
    image: application-service:latest
    restart: on-failure
    depends_on:
      - application-mondodb
    ports:
      - 8082:8082
    networks:
      - blog-network
  
  static-service:
    container_name: static-service
    build:
      context: static-service
      dockerfile: Dockerfile
    image: static-service:latest
    restart: on-failure
    depends_on:
      - static-service-mondodb
    ports:
      - 8083:8083
    networks:
      - blog-network

  notification-service:
    container_name: notification-service
    build:
      context: notification-service
      dockerfile: Dockerfile
    image: notification-service:latest
    restart: on-failure
    depends_on:
      - notification-mondodb
    ports:
      - 8086:8086
    networks:
      - blog-network

  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    restart: on-failure
    ports:
      - 7000:7000
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
volumes:
  application-mongo:
  notification-mongo:
  static-service-mongo:
