version: '3.8'

services:

  application-mondodb:
    image: mongo
    ports: 
      - "27017:27017"
    volumes: 
      - application-mongo:/data/db

  notification-mondodb:
    image: mongo
    ports: 
      - "27018:27017"
    volumes: 
      - notification-mongo:/data/db

  application-service:
    container_name: application-service
    build:
      context: application-service
      dockerfile: Dockerfile
    image: application-service:latest
    restart: on-failure
    ports:
      - 8082:8082
    networks:
      - blog-network
  
  static-service:
    container_name: static-service
    build:
      context: static-service
      dockerfile: Dockerfile
    image: static-service:latest
    restart: on-failure
    ports:
      - 8083:8083
    networks:
      - blog-network

  notification-service:
    container_name: notification-service
    build:
      context: notification-service
      dockerfile: Dockerfile
    image: notification-service:latest
    restart: on-failure
    ports:
      - 8086:8086
    networks:
      - blog-network

  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    restart: on-failure
    depends_on:
      - service-registry
      - config-service
    ports:
      - 7000:7000
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
volumes:
  application-mongo:
  notification-mongo:
