
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
            - id: application-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/app/**
            - id: static-service
              uri: http://localhost:8083
              predicates:
                - Path=/static/**
            - id: notification-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/v1/notification/**