
spring:
  application:
    name: api-gateway
  config:
    import:
    - configserver:http://config-service:8099
  cloud:
    gateway:
        routes:
            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/api/v1/app/**
            - id: static-service
              uri: lb://static-service
              predicates:
                - Path=/static/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notification/**