
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
            - id: application-service
              uri: ${APPLICATION_SERVICE_BASE}
              predicates:
                - Path=/api/v1/app/**
            - id: static-service
              uri: ${STATIC_SERVICE_BASE}
              predicates:
                - Path=/static/**
            - id: notification-service
              uri: ${NOTIFICATION_SERVICE}
              predicates:
                - Path=/api/v1/notification/**