
spring:
    application:
        name: static-service
    config:
        import: "configserver:http://config-service:8099"

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        url: jdbc:mysql://static-service-mysql:3306/static_server
        username: root
        password: root@123
        driver-class-name: com.mysql.cj.jdbc.Driver
        
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://accounts.google.com
                    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

logging:
    level:
        org:
            springframework:
                security: trace
